I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mini_game/quiz.rpy", line 1, in script
    init python:
  File "game/mini_game/quiz.rpy", line 7, in <module>
    questions = json.load(renpy.file("./quiz.json"))
OSError: Couldn't find file './quiz.json'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mini_game/quiz.rpy", line 1, in script
    init python:
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\fanbase_project\KTPVisualNovel\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/mini_game/quiz.rpy", line 7, in <module>
    questions = json.load(renpy.file("./quiz.json"))
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 2641, in file
    return open_file(fn, encoding=encoding)
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 2623, in open_file
    rv = renpy.loader.load(fn, directory=directory)
  File "D:\fanbase_project\KTPVisualNovel\renpy\loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file './quiz.json'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
WGV Filles La Dreamcatcher 
Wed May  1 18:43:51 2024
