I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 70, in script
    scene white pause 1.0
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 70, in script
    scene white pause 1.0
Exception: Image 'white' does not accept attributes 'pause 1 .0'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\fanbase_project\KTPVisualNovel\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\fanbase_project\KTPVisualNovel\renpy\main.py", line 635, in main
    run(restart)
  File "D:\fanbase_project\KTPVisualNovel\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "D:\fanbase_project\KTPVisualNovel\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 70, in script
    scene white pause 1.0
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 241, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 70, in script
    scene white pause 1.0
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1247, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'white' does not accept attributes 'pause 1 .0'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
WGV Filles La Dreamcatcher 
Mon Apr 29 20:47:40 2024
